const db = require ("./database_common")
const pw = require("./MyHasher")
console.log(pw.PasswordHash('mango'))
console.log(pw.MatchPasswordHash('mango','banana'))
console.log(db.database)
console.log(db.username)
console.log(db.password)
console.log(db.Name)
console.log(db.port)